/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
52.
* This class is generated by the NetBeans IDE,
53.
* and registers all REST root resources created in the project.
54.
* Please, DO NOT EDIT this class unless you really need and
55.
* understand the results of changes.
56.
* It is safe to change REST resources path value of
57.
* ApplicationPath annotation. It can be done also via UI action
58.
* called on RESTful Web Services node ( REST Resources Configuration dialog ).
59.
*
60.
*/
package org.netbeans.rest.application.config;

import java.util.Set;
import javax.ws.rs.core.Application;
//rest web resources
/**
 *
 * @author SUDHANSHU
 */
@javax.ws.rs.ApplicationPath("webresources")
public class ApplicationConfig extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        Set<Class<?>> resources = new java.util.HashSet<>();
        addRestResourceClasses(resources);
        return resources;
    }

    /**
     * Do not modify addRestResourceClasses() method.
     * It is automatically populated with
     * all resources defined in the project.
     * If required, comment out calling this method in getClasses().
     */
    private void addRestResourceClasses(Set<Class<?>> resources) {
        resources.add(businessCharts.BusinessResource.class);
        resources.add(mission.NewCrossOriginResourceSharingFilter.class);
        resources.add(mission.RestMappingEntry.class);
    }
    
}
